# Use a minimal Python base image
FROM python:3.11-slim

# Add a new group and user before all
RUN addgroup invest \
    && adduser --disabled-password --gecos "" pipline \
    && adduser pipline invest

# Set environment variables to avoid warnings about Python script locations
ENV PATH="/home/pipline/.local/bin:$PATH"

# Switch to a less privileged user
USER pipline

# Set working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt ./

# Install all dependencies in one step without caching build artifacts
RUN pip install --no-cache-dir -r requirements.txt

# Copy application source files
# COPY common.py ./ 
COPY pipeline.py ./
COPY investor_agent/ ./investor_agent/

# Run the Python script
CMD ["python", "./pipeline.py"]
