FROM python:3.11-slim

WORKDIR /app

RUN echo "$(cat .env.prod)" > /app/.env

COPY . /app

ENV GOOGLE_APPLICATION_CREDENTIALS="/app/sa.json"

RUN pip install -r requirements.txt

CMD ["python", "./pipeline.py"]
